[project]
name = "model-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "bpy>=4.4.0",
    "tyro>=0.9.20",
]

[tool.ruff]
lint.select = ["E", "F", "I", "PLC", "PLE", "PLR", "PLW"]
lint.ignore = ["PLR0913"]
